### ISSUE TITLE
Make it possible to start VertxSliceServer on random port

### ISSUE THREAD

**Issue by olegmoz** [artipie/vertx-server#11]
Starting VertxSliceServer on random server is very useful in tests

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Sammers21** [comment]
@olegmoz , close the issue

**Comment by 0crat** [comment]
Job `gh:artipie/vertx-server#11` is not assigned, can't get performer
