### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by g4s8** [artipie/vertx-server#12]
Update http version to latest

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 53 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [593ac955-8a6a-4c37-8098-91eea11452ad](https://www.0crat.com/footprint/CT2E6TK9B/593ac955-8a6a-4c37-8098-91eea11452ad), Type: "Request order start"

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@brastak it was released: https://github.com/artipie/vertx-server/issues/12#issuecomment-617199826

**Comment by 0crat** [comment]
Job `gh:artipie/vertx-server#12` is not assigned, can't get performer
