### ISSUE TITLE
`Content-Length` header conflicts with `Transfer-Encoding`

### ISSUE THREAD

**Issue by olegmoz** [artipie/vertx-server#26]
Vert.x server adds `Transfer-Encoding: chunked` header to every response. However by HTTP standards it should not be done if `Content-Length` header presents in response. Some HTTP clients fail to handle responses from Vert.x server due to violation of this rule. We should not add `Transfer-Encoding: chunked` header if `Content-Length` header is already there.

**Comment by olegmoz** [comment]
@Sammers21 interested in taking on this one?

**Comment by Sammers21** [comment]
@olegmoz, sure, I will take care of it.

**Comment by Sammers21** [comment]
@olegmoz, I guess we should always unset `Content-Length` header?

**Comment by olegmoz** [comment]
@Sammers21 of course not, Content-Length is required by many protocols. We should not add Transfer-Encoding if Content-Length is present

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@yegor256 could you please touch `.rultor.yml`, we need to release this module

**Comment by yegor256** [comment]
@olegmoz done in 098b68a

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.4`
