### ISSUE TITLE
`HttpServer` with custom `HttpServerOptions`

### ISSUE THREAD

**Issue by dgarus** [artipie/vertx-server#29]
This is needed for [artipie/http-client#9](https://github.com/artipie/http-client/issues/9).

`VertxSliceServer` should be able to create `HttpServer` with custom `HttpServerOptions`.
So we could configure the server with SSL.

**Comment by kirill-h5i** [comment]
@g4s8 please handle

**Comment by dgarus** [comment]
@g4s8 hi!
Could you please have a look?

**Comment by g4s8** [comment]
@dgarus the version `1.0.0` was released: https://github.com/artipie/vertx-server/releases/tag/1.0.0 - it should be available on Maven central in a few minutes
