### ISSUE TITLE
Warning: You're already on a Vert.x context, are you sure you want to create a new Vertx instance?

### ISSUE THREAD

**Issue by g4s8** [artipie/vertx-server#6]
Each HTTP request produces this warning message in logs. Let's investigate how critical it is:
```
APP vert.x-eventloop-thread-0 com.artipie.RepoConfig: using file storage at /tmp/artipie/repos/simple
Feb 21, 2020 12:42:52 PM io.vertx.core.impl.VertxImpl
WARNING: You're already on a Vert.x context, are you sure you want to create a new Vertx instance?
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/vertx-server/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/vertx-server` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/vertx-server` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by Sammers21** [comment]
@g4s8 , close it as invalid

**Comment by g4s8** [comment]
> @g4s8 , close it as invalid

@Sammers21 can you add a comment about  it, why it's invalid?

**Comment by Sammers21** [comment]
@g4s8, on the prev version of RxFile, new event loop were created on each request.

**Comment by 0crat** [comment]
Job `gh:artipie/vertx-server#6` is not assigned, can't get performer
